version: '3.9'

services:
# redis for cache
  redis-bayut:
      image: redis:alpine
      container_name: redis-bayut-v1
      restart: always
      volumes:
        - ./server/redis-data:/data
      networks:
        - bayut

# nodejs for api calls and caching data in redis 
  backend:
    build: 
      context: ./server
    restart: always
    container_name: bayut-api-v1
    networks:
      - bayut
    env_file:
      - ./server/.env
    depends_on:
      - redis-bayut

# nextjs for frontend 
  bayut-client:
      container_name: bayut-client
      build: 
        context: ./client
      restart: always
      volumes:
        - next_build:/app/.next
      env_file:
        - ./client/.env.local
      networks:
        - bayut
      depends_on:
        - backend

# negix web server 
  nginx:
    image: nginx:latest
    container_name: bayut-nginx
    restart: always
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - next_build:/var/www/app
    networks:
      - bayut
    depends_on:
      - bayut-client

networks:
  bayut:
    external: true
volumes:
  next_build:
